local OrionLib = loadstring(game:HttpGet(('https://raw.githubusercontent.com/shlexware/Orion/main/source')))()

local Window = OrionLib:MakeWindow({Name = "Tapping Legends X | Stellar Hub", HidePremium = false, SaveConfig = true, ConfigFolder = "StellarHubClickSim", IntroText = "Stellar Hub Community Edition"})

--[[
Name = <string> - The name of the UI.
HidePremium = <bool> - Whether or not the user details shows Premium status or not.
SaveConfig = <bool> - Toggles the config saving in the UI.
ConfigFolder = <string> - The name of the folder where the configs are saved.
IntroEnabled = <bool> - Whether or not to show the intro animation.
IntroText = <string> - Text to show in the intro animation.
IntroIcon = <string> - URL to the image you want to use in the intro animation.
Icon = <string> - URL to the image you want displayed on the window.
CloseCallback = <function> - Function to execute when the window is closed.
]]


--Values
_G.MassiveClicking = false
_G.AutoRebirth = false
_G.AutoClaimRewards = false
--fncs

function massiveClick()
   while _G.MassiveClicking == true do
   game:GetService("ReplicatedStorage").Remotes.Tap:FireServer()
   wait(0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001)
end
end

function autorebirth()
 while _G.AutoRebirth == true do
game:GetService("ReplicatedStorage").Remotes.Rebirth:FireServer(1)
wait(1)
end
end

function autoclaimrewards()
if _G.AutoClaimRewards == true then
	OrionLib:MakeNotification({
	Name = "Enabled!",
	Content = "Auto-Claim Rewards Only Work Every 32 Minutes.",
	Image = "rbxassetid://4483345998",
	Time = 5
})
end

while _G.AutoClaimRewards == true do

-- Script generated by TurtleSpy, made by Intrer#0421
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(1)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(2)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(3)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(4)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(5)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(6)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(7)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(8)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(9)
wait(60 * 32)
while _G.AutoClaimRewards == true do
-- Script generated by TurtleSpy, made by Intrer#0421
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(1)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(2)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(3)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(4)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(5)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(6)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(7)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(8)
game:GetService("ReplicatedStorage").Remotes.PlaytimeReward:FireServer(9)
end
end
end


local AutoFarmTab = Window:MakeTab({
	Name = "Autofarm",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})




local AutoFarmSection = AutoFarmTab:AddSection({
	Name = "Fun"
})

--[[
Name = <string> - The name of the section.
]]
--[[
Name = <string> - The name of the tab.
Icon = <string> - The icon of the tab.
PremiumOnly = <bool> - Makes the tab accessible to Sirus Premium users only.
]]

AutoFarmSection:AddToggle({
	Name = "Mass Clicking",
	Default = false,
	Callback = function(Value)
    _G.MassiveClicking = Value
    massiveClick()

end
})

AutoFarmSection:AddToggle({
	Name = "Auto Rebirth",
	Default = false,
	Callback = function(Value)
    _G.AutoRebirth = Value
    autorebirth()

end
})
--[[
Name = <string> - The name of the toggle.
Default = <bool> - The default value of the toggle.
Callback = <function> - The function of the toggle.
]]

local Automation = AutoFarmTab:AddSection({
	Name = "Automation"
})


Automation:AddToggle({
	Name = "Auto-Claim Rewards",
	Default = false,
	Callback = function(Value)
		_G.AutoClaimRewards = Value
        autoclaimrewards()
        
end
})

Automation:AddLabel("More Features Are Coming Soon ~ Stellar Owner")
--[[
Title = <string> - The title of the notification.
Content = <string> - The content of the notification.
Image = <string> - The icon of the notification.
Time = <number> - The duration of the notfication.
]]


--[[
Name = <string> - The name of the toggle.
Default = <bool> - The default value of the toggle.
Callback = <function> - The function of the toggle.
]]
--[[
Name = <string> - The name of the section.
]]

local TeleportTabs = Window:MakeTab({
	Name = "Teleport",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})

--[[
Name = <string> - The name of the tab.
Icon = <string> - The icon of the tab.
PremiumOnly = <bool> - Makes the tab accessible to Sirus Premium users only.
]]

local TeleportSection = TeleportTabs:AddSection({
	Name = "Teleports"
})

--[[
Name = <string> - The name of the section.
]]

TeleportSection:AddButton({
	Name = "Rewards Chest",
	Callback = function()
      	local player = game:GetService("Players").LocalPlayer

if player.Character then
    local newPosition = Vector3.new(-15, 155, -879)
    player.Character.PrimaryPart.CFrame = CFrame.new(newPosition)
end

  	end    
})


TeleportSection:AddButton({
	Name = "Upgrades",
	Callback = function()
      	local player = game:GetService("Players").LocalPlayer

if player.Character then
    local newPosition = Vector3.new(-76, 144, -715)
    player.Character.PrimaryPart.CFrame = CFrame.new(newPosition)
end

  	end    
})

TeleportSection:AddButton({
	Name = "Worlds",
	Callback = function()
      	local player = game:GetService("Players").LocalPlayer

if player.Character then
    local newPosition = Vector3.new(8,166,-1014)
    player.Character.PrimaryPart.CFrame = CFrame.new(newPosition)
end

  	end    
})

TeleportSection:AddButton({
	Name = "Leaderboards",
	Callback = function()
      	local player = game:GetService("Players").LocalPlayer

if player.Character then
    local newPosition = Vector3.new(113,146,-673)
    player.Character.PrimaryPart.CFrame = CFrame.new(newPosition)
end

  	end    
})


--[[
Name = <string> - The name of the button.
Callback = <function> - The function of the button.
]]


OrionLib:Init()
